### ISSUE TITLE
Missing gpth-3.6.2-linux-arm64 version

### ISSUE THREAD

**Issue by jaimetur** [Wacheee/GooglePhotosTakeoutHelper#19]
I would suggest to include gpth-3.6.2-linux-arm64.bin binary version to the set of pre-compiled binaries to complete the whole set of current SO and Architectures.

On the other hand, it would be good to unificate the names of the files for a better understanding, and 3rd parties integrations, something like this would be perfect:

gpth-3.6.2-linux-amd64.bin
gpth-3.6.2-linux-arm64.bin (missing)
gpth-3.6.2-macos-amd64.bin
gpth-3.6.2-macos-arm64.bin
gpth-3.6.2-windows-amd64.exe

Modify GitHub Actions to generate binaries for windows, macos, linux for both amd64 (x64) and arm64

This can be done easily with GitHub Actions using a matrix strategic like this:

```
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # os list
        arch: [x86_64, arm64]  # arch list
        exclude:
          - os: windows-latest
            arch: arm64  # Windows is only compiled for x86 (32/64-bit)

    runs-on: ${{ matrix.os }}
```

**Comment by Xentraxx** [comment]
Fixed here: https://github.com/Xentraxx/GooglePhotosTakeoutHelper/

**Comment by Wacheee** [comment]
This a a bit tricky, this code won't work.
```
os: [ubuntu-latest, macos-latest, windows-latest]  # os list
        arch: [x86_64, arm64]  # arch list
```
This is because `ubuntu-latest` and `macos-latest` are VMs with a fixed architecture (https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories). Dart generates an executable for the architecture of the build machine. To handle both Intel and ARM correctly, you must use:

`macos-13` for Intel macOS (already used in GPTH v3.6.2)

`ubuntu-24.04-arm` for ARM64 linux

@Xentraxx 
The GPTH 4.x.x executables for each OS currently have the same file size regardless of architecture. That’s because the workflow isn’t actually building separate binaries per architecture, as noted above.

![Image](https://github.com/user-attachments/assets/2edfb7d1-40ea-4ac0-a380-ea7fa2797bce)

I don't know where to put this issue as is for 4.x.x version...

**Comment by Wacheee** [comment]
> I would suggest to include gpth-3.6.2-linux-arm64.bin binary version to the set of pre-compiled binaries to complete the whole set of current SO and Architectures.
> 
> On the other hand, it would be good to unificate the names of the files for a better understanding, and 3rd parties integrations, something like this would be perfect:
> 
> gpth-3.6.2-linux-amd64.bin gpth-3.6.2-linux-arm64.bin (missing) gpth-3.6.2-macos-amd64.bin gpth-3.6.2-macos-arm64.bin gpth-3.6.2-windows-amd64.exe
> 
> Modify GitHub Actions to generate binaries for windows, macos, linux for both amd64 (x64) and arm64
> 
> This can be done easily with GitHub Actions using a matrix strategic like this:
> 
> ```
> jobs:
>   build:
>     strategy:
>       matrix:
>         os: [ubuntu-latest, macos-latest, windows-latest]  # os list
>         arch: [x86_64, arm64]  # arch list
>         exclude:
>           - os: windows-latest
>             arch: arm64  # Windows is only compiled for x86 (32/64-bit)
> 
>     runs-on: ${{ matrix.os }}
> ```

For file names, I’m sticking to the original author’s naming convention for now, but I can rename them later if needed.
Regarding Linux arm64, I’ll try adding it with the `ubuntu-24.04-arm` tag I mentioned before.

**Comment by Xentraxx** [comment]
Fixed it in my 4.0.2 branch for nightly and release build.
See https://github.com/Xentraxx/GooglePhotosTakeoutHelper/actions/runs/15273757360

**Comment by jaimetur** [comment]
This is the right matrix to use:

```

jobs:
  build:
    strategy:
      matrix:
        include:
          # macOS
          - os: macos-13
            arch: x86_64
            runs-on: macos-13

          - os: macos-latest
            arch: arm64
            runs-on: macos-latest

          # Linux
          - os: ubuntu-24.04
            arch: x86_64
            runs-on: ubuntu-24.04

          - os: ubuntu-24.04-arm
            arch: arm64
            runs-on: ubuntu-24.04-arm

          # Windows
          - os: windows-latest
            arch: x86_64
            runs-on: windows-latest

          - os: windows-11-arm
            arch: arm64
            runs-on: windows-11-arm

    runs-on: ${{ matrix.runs-on }}

```
